version: '3.8'

services:
  tp-link-snmp-gateway:
    container_name: tplink-snmp-gateway
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: kenconex/web-snmp-converter:latest
    env_file:
      - ./.env # Ini .env tetep di dalam dockge soalnya
      # - .env
      # - "/root/Docker_mee/000_NetBird_VPN/dashboard.env"
    # Host networking is recommended for SNMP agents so all dynamic UDP ports
    # are directly accessible to Zabbix without manual port forwarding:
    # network_mode: "host"
    #
    # Alternatively, map specific UDP/TCP ports as below:
    ports:
      - "6262:8080/tcp"          # Web Dashboard
      - "6161-6180:6161-6180/udp"    # Dynamic SNMP Ports for 12+ Switches (161=Switch 1 ... 172=Switch 12)
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      wb-snmp-net:
        ipv4_address: 10.101.26.2
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      autoheal-this-app: "true"
    restart: unless-stopped


networks:
  wb-snmp-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: wb-snmp-net
    ipam:
      driver: default
      config:
        - subnet: 10.101.26.0/24
          gateway: 10.101.26.1
